# Minecraft server image.
#
# This file is the version-agnostic base. Per-version data (upstream version
# strings, server JAR hash, mod selection) lives in `./versions.nix` as
# overlay modules layered on top of this one by `lib.discoverImages`.
#
# Cross-version baseline mods come from ./mods/common.json (a slug-keyed
# catalog generated by tools/update-mods.py). Every variant gets these for
# free; per-version mods are added by the version overlay.
{ lib, ... }:
let
  commonCatalog = builtins.fromJSON (builtins.readFile ./mods/common.json);
in
{
  ix.image.name = "minecraft";

  services.minecraft = {
    enable = true;
    serverProperties = {
      motd = "ix-powered Minecraft";
      max-players = 20;
    };
    mods = lib.mapAttrs (_: _: { }) commonCatalog;
    modCatalog = commonCatalog;
  };
}
