# Minecraft server image.
#
# This file is the version-agnostic base. Per-version data (upstream version
# strings, server JAR hash, version-specific mods) lives in `./versions.nix`
# as overlay modules layered on top of this one by `lib.discoverImages`.
#
# Cross-version baseline mods come from ./mods/common.json (generated by
# tools/update-mods.py). Version-specific mods live in ./mods/<ver>.json.
# Module merge concatenates both lists.
{ pkgs, ... }:
{
  ix.image.name = "minecraft";

  services.minecraft = {
    enable = true;
    serverProperties = {
      motd = "ix-powered Minecraft";
      max-players = "20";
    };
    mods = map pkgs.fetchurl (builtins.fromJSON (builtins.readFile ./mods/common.json));
  };
}
