# Versioned overlays for the minecraft image.
#
# Discovery exposes `minecraft_<key>` for every version key and `minecraft` as
# an alias for the version named in `default`.
#
# Each variant picks mods by Modrinth slug in `services.minecraft.mods`.
# The per-version catalog is loaded from ./mods/<minecraftVersion>.json
# (generated by tools/update-mods.py). Cross-version baseline mods come from
# ./mods/common.json via the image base (./default.nix).
{ lib, ... }:
let
  default = "26w17a-fabric";

  catalogFor = ver: builtins.fromJSON (builtins.readFile ./mods/${ver}.json);

  variants = {
    "26w17a-fabric" = {
      loader = "fabric";
      minecraftVersion = "26.2-snapshot-5";
      loaderVersion = "0.19.2";
      installerVersion = "1.1.1";
      hash = "sha256-IZctWQu9VH4Z5lU/VcEzvPGLfW8boOAXtCaQlKXyA5k=";
      mods = [
        "fabric-api"
        "c2me-fabric"
      ];
    };

    "26.1.2-fabric" = {
      loader = "fabric";
      minecraftVersion = "26.1.2";
      loaderVersion = "0.19.2";
      installerVersion = "1.1.1";
      hash = "sha256-6RvRm5/w4ExXhD5iTS9U0KPjmgSMr8pejiDrmENEXb0=";
      mods = [
        "fabric-api"
        "lithium"
        "c2me-fabric"
        "krypton"
        "ferrite-core"
        "distanthorizons"
        "servercore"
        "vmp-fabric"
        "clumps"
        "chunky"
        "bluemap"
        "luckperms"
        "simple-voice-chat"
        "spark"
      ];
    };
  };

  mkVariant =
    tag:
    {
      loader,
      mods,
      minecraftVersion,
      ...
    }@cfg:
    let
      loaderCfg = builtins.removeAttrs cfg [ "loader" "mods" "minecraftVersion" ];
    in
    {
      ix.image.tag = tag;
      services.minecraft = {
        mods = lib.genAttrs mods (_: { });
        modCatalog = catalogFor minecraftVersion;
      };
      services.minecraft.${loader} = loaderCfg // {
        enable = true;
      };
    };
in
{
  inherit default;
}
// lib.mapAttrs mkVariant variants
