# Versioned overlays for the minecraft image.
#
# Discovery exposes `minecraft_<key>` for every version key and `minecraft` as
# an alias for the version named in `default`.
#
# Each variant picks mods by Modrinth slug. The catalog for each game version
# is loaded automatically from ./mods/<minecraftVersion>.json (slug-keyed,
# generated by tools/update-mods.py). Cross-version baseline mods come from
# ./mods/common.json via the image base (./default.nix).
{ lib, ... }:
let
  default = "26w17a-fabric";

  catalogFor = ver: builtins.fromJSON (builtins.readFile ./mods/${ver}.json);

  variants = {
    "26w17a-fabric" = {
      loader = "fabric";
      minecraftVersion = "26.2-snapshot-5";
      loaderVersion = "0.19.2";
      installerVersion = "1.1.1";
      hash = "sha256-IZctWQu9VH4Z5lU/VcEzvPGLfW8boOAXtCaQlKXyA5k=";
      mods = [
        "fabric-api"
        "c2me-fabric"
      ];
    };

    "26.1.2-fabric" = {
      loader = "fabric";
      minecraftVersion = "26.1.2";
      loaderVersion = "0.19.2";
      installerVersion = "1.1.1";
      hash = "sha256-6RvRm5/w4ExXhD5iTS9U0KPjmgSMr8pejiDrmENEXb0=";
      mods = [
        "fabric-api"
        "lithium"
        "c2me-fabric"
        "krypton"
        "ferrite-core"
      ];
    };
  };

  mkVariant =
    tag:
    {
      loader,
      ...
    }@cfg:
    {
      ix.image.tag = tag;
      services.minecraft.${loader} = (builtins.removeAttrs cfg [ "loader" ]) // {
        enable = true;
        modCatalog = catalogFor cfg.minecraftVersion;
      };
    };
in
{
  inherit default;
}
// lib.mapAttrs mkVariant variants
