# Helper for declaring a minecraft loader module (Fabric, Paper, Vanilla, ...).
#
# Each loader is structurally identical: declare options under
# `services.minecraft.<name>`, fetch a server jar, and assign it to
# `services.minecraft.serverJar`. Only the URL shape and the per-loader
# fields differ.
#
# Mods are user-selected by slug. The image (or version overlay) supplies a
# `modCatalog` mapping slug -> { url, hash } and a `mods` list of slugs to
# include. The helper resolves slugs to fetchurl derivations and assigns the
# result to `services.minecraft.mods`. Catalogs are produced by
# `tools/update-mods.py` and committed under `images/games/minecraft/mods/`.
#
# Reached from modules via `specialArgs.ix.mkMinecraftLoader`. Loader files
# call it and return the resulting module attrset directly.
{
  config,
  lib,
  pkgs,
  name,
  urlFor,
  dropDir ? "mods",
  extraOptions ? { },
}:
let
  cfg = config.services.minecraft.${name};
  modAttrType = lib.types.submodule {
    options = {
      url = lib.mkOption { type = lib.types.str; };
      hash = lib.mkOption { type = lib.types.str; };
    };
  };
in
{
  options.services.minecraft.${name} = {
    enable = lib.mkEnableOption "${name} server jar";
    hash = lib.mkOption {
      type = lib.types.str;
      description = "SRI hash of the server jar.";
    };
    mods = lib.mkOption {
      type = lib.types.listOf lib.types.str;
      default = [ ];
      description = "Mod slugs to include from `modCatalog`.";
      example = [
        "lithium"
        "krypton"
      ];
    };
    modCatalog = lib.mkOption {
      type = lib.types.attrsOf modAttrType;
      default = { };
      description = "Slug -> { url, hash } catalog generated by tools/update-mods.py.";
    };
  }
  // extraOptions;

  config = lib.mkIf cfg.enable {
    services.minecraft.enable = lib.mkDefault true;
    services.minecraft.dropDir = lib.mkDefault dropDir;
    services.minecraft.serverJar = pkgs.fetchurl {
      url = urlFor cfg;
      inherit (cfg) hash;
    };
    services.minecraft.mods = map (
      slug:
      let
        entry = cfg.modCatalog.${slug} or (throw "mod '${slug}' not in ${name} catalog");
      in
      pkgs.fetchurl entry
    ) (cfg.mods ++ config.services.minecraft.extraModSlugs);
  };
}
